title: Site

columns:
  # The first column has one section for the subpages of the `photography` page in card layout
  # It reuses the pages section defined in `/site/blueprints/sections/albums.yml`
  - width: 1/2
      sections:
        albums: sections/items

  - width: 1/2
      sections:
        siteInfo:
          template:
            - home
            - a-propos
          label: " "
          type: pages
          exclude: hidden-page
          create: false # Exclut la page parente spécifique


